#spring
spring:
  datasource:
     name: dev
     url: jdbc:mysql://localhost:3306/test-bike
     username: root
     password: root
  #activeQE
  activemq:
    broker-url: tcp://localhost:61616
    pool:
      enabled: false
  #mongodb
  data:
    mongodb:
      uri: mongodb://localhost:27017/test-bike



#redis
redis:
  host: 127.0.0.1
  port: 6379
  auth:
  max-idle: 5
  max-total: 10
  max-wait-millis: 3000

